# Generated by Django 3.2.3 on 2021-05-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='name',
            new_name='product',
        ),
    ]
