# Generated by Django 3.2.3 on 2021-05-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_rename_name_mall_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='body',
            new_name='description',
        ),
    ]
